### ISSUE TITLE
Searching and filtering doesn't appear to work

### ISSUE THREAD

**Issue by jarradraumati** [danyill/oscd-subscriber-later-binding#35]
![image](https://github.com/danyill/oscd-subscriber-later-binding/assets/3224671/a3d8206b-2ec4-4643-8f89-fcec4e710961)

If you untick the "Subscribed" filter with a search term already entered, it will show IEDs with no ExtRefs. I think it would be desirable to not show IEDs that don't meet the search criteria.

Here is a file to replicate.

[XAT (11).zip](https://github.com/danyill/oscd-subscriber-later-binding/files/13290067/XAT.11.zip)

**Comment by danyill** [comment]
Thanks for the reproduction case, I'll update our distribution shortly - would appreciate a little testing of search + filter combinations.

**Comment by jarradraumati** [comment]
I am unable to reproduce. Thanks.
