### ISSUE TITLE
Data attributes with different CDCs do not automatically map the quality bit upon subscription

### ISSUE THREAD

**Issue by jarradraumati** [danyill/oscd-subscriber-later-binding#37]
Referring to disabling of CDC checks (see https://github.com/OpenEnergyTools/scl-lib/pull/66)
and https://github.com/jarradraumati/oscd-subscriber-later-binding/tree/disable-extref-restriction

When I map a `general` data attribute onto a `stVal` ExtRef, the quality bit within the data object is not automatically mapped.

Here is a video of the behaviour:

https://github.com/danyill/oscd-subscriber-later-binding/assets/3224671/851bdb8d-4dbe-4046-bed1-d0f2550657ec

[XAT (10).zip](https://github.com/danyill/oscd-subscriber-later-binding/files/13312684/XAT.10.zip)

**Comment by danyill** [comment]
Yup. I think that becomes an issue here: https://github.com/danyill/oscd-subscriber-lb-siemens

Because other than the "first one", the quality or other phases etc. is done by the other menu plugin. I'll file a stub issue there.

**Comment by danyill** [comment]
To achieve this we need to reflect the "basic type check" onto the element and then respond to that in the `oscd-subscriber-lb-siemens` plugin.

I'll close this in favour of that issue and [reflect the attribute ](https://lit.dev/docs/components/properties/#reflected-attributes) as part of dealing with #10.
